---
## { "ansible_operator_meta": {
##      "name": <object_name>,
##      "namespace": <object_namespace>,
##   },
##   <cr_spec_fields_as_snake_case>,
##   <watch vars>,
##   <finalizer vars>,
##   _<group_as_snake>_<kind>: {
##       <cr_object> as is
##   }
##   _<group_as_snake>_<kind>_spec: {
##       <cr_object.spec> as is
##   }
## }
# yamllint disable-line rule:line-length
group_kind: "Group"
# yamllint disable-line rule:line-length
group_api_group: "tower.ansible.com"
# yamllint disable-line rule:line-length
group_api_version: "v1alpha1"
# yamllint disable-line rule:line-length
group_finalize_state: "{{ finalize_state | default('present', true) }}"
# yamllint disable-line rule:line-length
group_metadata_name: "{{ ansible_operator_meta.name }}"
# yamllint disable-line rule:line-length
group_metadata_namespace: "{{ ansible_operator_meta.namespace }}"
# yamllint disable-line rule:line-length
group_module_name: "tower_group"
# yamllint disable-line rule:line-length
group_spec: "{{ _tower_ansible_com_group.spec }}"
# yamllint disable-line rule:line-length
group_spec_collection: "{{ group_spec.collection | default('awx.awx') }}"
# yamllint disable-line rule:line-length
group_spec_config: "{{ group_spec.config | combine({'state': group_finalize_state}) }}"
# yamllint disable-line rule:line-length
group_spec_secret: "{{ group_spec.secret | mandatory }}"
