---
## { "ansible_operator_meta": {
##      "name": <object_name>,
##      "namespace": <object_namespace>,
##   },
##   <cr_spec_fields_as_snake_case>,
##   <watch vars>,
##   <finalizer vars>,
##   _<group_as_snake>_<kind>: {
##       <cr_object> as is
##   }
##   _<group_as_snake>_<kind>_spec: {
##       <cr_object.spec> as is
##   }
## }
# yamllint disable-line rule:line-length
role_kind: "Role"
# yamllint disable-line rule:line-length
role_api_group: "tower.ansible.com"
# yamllint disable-line rule:line-length
role_api_version: "v1alpha1"
# yamllint disable-line rule:line-length
role_finalize_state: "{{ finalize_state | default('present', true) }}"
# yamllint disable-line rule:line-length
role_metadata_name: "{{ ansible_operator_meta.name }}"
# yamllint disable-line rule:line-length
role_metadata_namespace: "{{ ansible_operator_meta.namespace }}"
# yamllint disable-line rule:line-length
role_module_name: "tower_role"
# yamllint disable-line rule:line-length
role_spec: "{{ _tower_ansible_com_role.spec }}"
# yamllint disable-line rule:line-length
role_spec_collection: "{{ role_spec.collection | default('awx.awx') }}"
# yamllint disable-line rule:line-length
role_spec_config: "{{ role_spec.config | combine({'state': role_finalize_state}) }}"
# yamllint disable-line rule:line-length
role_spec_secret: "{{ role_spec.secret | mandatory }}"
