---
## { "ansible_operator_meta": {
##      "name": <object_name>,
##      "namespace": <object_namespace>,
##   },
##   <cr_spec_fields_as_snake_case>,
##   <watch vars>,
##   <finalizer vars>,
##   _<group_as_snake>_<kind>: {
##       <cr_object> as is
##   }
##   _<group_as_snake>_<kind>_spec: {
##       <cr_object.spec> as is
##   }
## }
# yamllint disable-line rule:line-length
project_kind: "Project"
# yamllint disable-line rule:line-length
project_api_group: "tower.ansible.com"
# yamllint disable-line rule:line-length
project_api_version: "v1alpha1"
# yamllint disable-line rule:line-length
project_finalize_state: "{{ finalize_state | default('present', true) }}"
# yamllint disable-line rule:line-length
project_metadata_name: "{{ ansible_operator_meta.name }}"
# yamllint disable-line rule:line-length
project_metadata_namespace: "{{ ansible_operator_meta.namespace }}"
# yamllint disable-line rule:line-length
project_module_name: "tower_project"
# yamllint disable-line rule:line-length
project_spec: "{{ _tower_ansible_com_project.spec }}"
# yamllint disable-line rule:line-length
project_spec_collection: "{{ project_spec.collection | default('awx.awx') }}"
# yamllint disable-line rule:line-length
project_spec_config: "{{ project_spec.config | combine({'state': project_finalize_state}) }}"
# yamllint disable-line rule:line-length
project_spec_secret: "{{ project_spec.secret | mandatory }}"
