---
- name: "Assert variables"
  assert:
    that:
      - user_kind is defined
      - user_kind is string
      - user_api_group is defined
      - user_api_group is string
      - user_api_version is defined
      - user_api_version is string
      - user_finalize_state is defined
      - user_finalize_state is in ['present', 'absent']
      - user_metadata_name is defined
      - user_metadata_name is string
      - user_metadata_namespace is defined
      - user_metadata_namespace is string
      - user_module_name is defined
      - user_module_name is in [ 'tower_user' ]
      - user_spec is defined
      - user_spec is mapping
      - user_spec_collection is defined
      - user_spec_collection is in ['awx.awx', 'ansible.tower']
      - user_spec_config is defined
      - user_spec_config is mapping

- name: "user: Calling desired state specific tasks"
  include_tasks: "{{ user_spec_config.state | default('present') }}.yml"
