---
- name: "Assert variables"
  assert:
    that:
      - credentialinputsource_kind is defined
      - credentialinputsource_kind is string
      - credentialinputsource_api_group is defined
      - credentialinputsource_api_group is string
      - credentialinputsource_api_version is defined
      - credentialinputsource_api_version is string
      - credentialinputsource_finalize_state is defined
      - credentialinputsource_finalize_state is in ['present', 'absent']
      - credentialinputsource_metadata_name is defined
      - credentialinputsource_metadata_name is string
      - credentialinputsource_metadata_namespace is defined
      - credentialinputsource_metadata_namespace is string
      - credentialinputsource_module_name is defined
      - credentialinputsource_module_name is in [ 'tower_credential_input_source' ]
      - credentialinputsource_spec is defined
      - credentialinputsource_spec is mapping
      - credentialinputsource_spec_collection is defined
      - credentialinputsource_spec_collection is in ['awx.awx', 'ansible.tower']
      - credentialinputsource_spec_config is defined
      - credentialinputsource_spec_config is mapping

- name: "credentialinputsource: Calling desired state specific tasks"
  include_tasks: "{{ credentialinputsource_spec_config.state | default('present') }}.yml"
