---
- name: "Assert variables"
  assert:
    that:
      - inventorysource_kind is defined
      - inventorysource_kind is string
      - inventorysource_api_group is defined
      - inventorysource_api_group is string
      - inventorysource_api_version is defined
      - inventorysource_api_version is string
      - inventorysource_finalize_state is defined
      - inventorysource_finalize_state is in ['present', 'absent']
      - inventorysource_metadata_name is defined
      - inventorysource_metadata_name is string
      - inventorysource_metadata_namespace is defined
      - inventorysource_metadata_namespace is string
      - inventorysource_module_name is defined
      - inventorysource_module_name is in [ 'tower_inventory_source' ]
      - inventorysource_spec is defined
      - inventorysource_spec is mapping
      - inventorysource_spec_collection is defined
      - inventorysource_spec_collection is in ['awx.awx', 'ansible.tower']
      - inventorysource_spec_config is defined
      - inventorysource_spec_config is mapping

- name: "inventorysource: Calling desired state specific tasks"
  include_tasks: "{{ inventorysource_spec_config.state | default('present') }}.yml"
