---
- name: "Assert variables"
  assert:
    that:
      - credential_kind is defined
      - credential_kind is string
      - credential_api_group is defined
      - credential_api_group is string
      - credential_api_version is defined
      - credential_api_version is string
      - credential_finalize_state is defined
      - credential_finalize_state is in ['present', 'absent']
      - credential_metadata_name is defined
      - credential_metadata_name is string
      - credential_metadata_namespace is defined
      - credential_metadata_namespace is string
      - credential_module_name is defined
      - credential_module_name is in [ 'tower_credential' ]
      - credential_spec is defined
      - credential_spec is mapping
      - credential_spec_collection is defined
      - credential_spec_collection is in ['awx.awx', 'ansible.tower']
      - credential_spec_config is defined
      - credential_spec_config is mapping

- name: "credential: Calling desired state specific tasks"
  include_tasks: "{{ credential_spec_config.state | default('present') }}.yml"
