# permissions for end users to view credentialtypes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: credentialtype-viewer-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - credentialtypes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - credentialtypes/status
  verbs:
  - get
