# permissions for end users to view credentialinputsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: credentialinputsource-viewer-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - credentialinputsources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - credentialinputsources/status
  verbs:
  - get
