# permissions for end users to edit credentialtypes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: credentialtype-editor-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - credentialtypes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - credentialtypes/status
  verbs:
  - get
