# permissions for end users to edit credentialinputsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: credentialinputsource-editor-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - credentialinputsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - credentialinputsources/status
  verbs:
  - get
