# permissions for end users to edit inventorysources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inventorysource-editor-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - inventorysources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - inventorysources/status
  verbs:
  - get
