# permissions for end users to view inventorysources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inventorysource-viewer-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - inventorysources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - inventorysources/status
  verbs:
  - get
