# permissions for end users to edit workflowjobtemplatenodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflowjobtemplatenode-editor-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - workflowjobtemplatenodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - workflowjobtemplatenodes/status
  verbs:
  - get
