# permissions for end users to view workflowjobtemplatenodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflowjobtemplatenode-viewer-role
rules:
- apiGroups:
  - tower.ansible.com
  resources:
  - workflowjobtemplatenodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tower.ansible.com
  resources:
  - workflowjobtemplatenodes/status
  verbs:
  - get
