---
## { "ansible_operator_meta": {
##      "name": <object_name>,
##      "namespace": <object_namespace>,
##   },
##   <cr_spec_fields_as_snake_case>,
##   <watch vars>,
##   <finalizer vars>,
##   _<group_as_snake>_<kind>: {
##       <cr_object> as is
##   }
##   _<group_as_snake>_<kind>_spec: {
##       <cr_object.spec> as is
##   }
## }
# yamllint disable-line rule:line-length
credential_kind: "Credential"
# yamllint disable-line rule:line-length
credential_api_group: "tower.ansible.com"
# yamllint disable-line rule:line-length
credential_api_version: "v1alpha1"
# yamllint disable-line rule:line-length
credential_finalize_state: "{{ finalize_state | default('present', true) }}"
# yamllint disable-line rule:line-length
credential_metadata_name: "{{ ansible_operator_meta.name }}"
# yamllint disable-line rule:line-length
credential_metadata_namespace: "{{ ansible_operator_meta.namespace }}"
# yamllint disable-line rule:line-length
credential_module_name: "tower_credential"
# yamllint disable-line rule:line-length
credential_spec: "{{ _tower_ansible_com_credential.spec }}"
# yamllint disable-line rule:line-length
credential_spec_collection: "{{ credential_spec.collection | default('awx.awx') }}"
# yamllint disable-line rule:line-length
credential_spec_config: "{{ credential_spec.config | combine({'state': credential_finalize_state}) }}"
# yamllint disable-line rule:line-length
credential_spec_secret: "{{ credential_spec.secret | mandatory }}"
