---
apiVersion: tower.ansible.com/v1alpha1
kind: Host
metadata:
  name: host-sample
spec:
  secret: toweraccess
  config:
    name: "{{ ansible_operator_meta.name }}"
    description: "Local Host Group"
    inventory: "inventory-sample"
    variables:
      example_var: 123

