---
apiVersion: tower.ansible.com/v1alpha1
kind: CredentialType
metadata:
  name: credentialtype-sample
spec:
  secret: toweraccess
  config:
    name: "{{ ansible_operator_meta.name }}"
    kind: net
    inputs:
      fields:
        - type: string
          id: username
          label: Username
        - type: string
          id: password
          label: Password
          secret: true
      required:
        - username
        - password
    injectors:
      env:
        # escaping     {{      and         }}
        USERNAME: "{%raw%}{{ username }}{%endraw%}"
        PASSWORD: "{%raw%}{{ password }}{%endraw%}"
