---
apiVersion: tower.ansible.com/v1alpha1
kind: Credential
metadata:
  name: credential-sample
spec:
  secret: toweraccess
  config:
      credential_type: Machine
      name: "{{ ansible_operator_meta.name }}"
      description: test
      organization: "organization-sample"
      inputs:
        username: test
        password: admintest
