---
apiVersion: tower.ansible.com/v1alpha1
kind: CredentialInputSource
metadata:
  name: credentialinputsource-sample
spec:
  secret: toweraccess
  config:
    input_field_name: password
    target_credential: new_cred
    source_credential: cyberark_lookup
    metadata:
      object_query: "Safe=MY_SAFE;Object=awxuser"
      object_query_format: "Exact"
