---
## { "ansible_operator_meta": {
##      "name": <object_name>,
##      "namespace": <object_namespace>,
##   },
##   <cr_spec_fields_as_snake_case>,
##   <watch vars>,
##   <finalizer vars>,
##   _<group_as_snake>_<kind>: {
##       <cr_object> as is
##   }
##   _<group_as_snake>_<kind>_spec: {
##       <cr_object.spec> as is
##   }
## }
# yamllint disable-line rule:line-length
credentialinputsource_kind: "CredentialInputSource"
# yamllint disable-line rule:line-length
credentialinputsource_api_group: "tower.ansible.com"
# yamllint disable-line rule:line-length
credentialinputsource_api_version: "v1alpha1"
# yamllint disable-line rule:line-length
credentialinputsource_finalize_state: "{{ finalize_state | default('present', true) }}"
# yamllint disable-line rule:line-length
credentialinputsource_metadata_name: "{{ ansible_operator_meta.name }}"
# yamllint disable-line rule:line-length
credentialinputsource_metadata_namespace: "{{ ansible_operator_meta.namespace }}"
# yamllint disable-line rule:line-length
credentialinputsource_module_name: "tower_credential_input_source"
# yamllint disable-line rule:line-length
credentialinputsource_spec: "{{ _tower_ansible_com_credentialinputsource.spec }}"
# yamllint disable-line rule:line-length
credentialinputsource_spec_collection: "{{ credentialinputsource_spec.collection | default('awx.awx') }}"
# yamllint disable-line rule:line-length
credentialinputsource_spec_config: "{{ credentialinputsource_spec.config | combine({'state': credentialinputsource_finalize_state}) }}"
# yamllint disable-line rule:line-length
credentialinputsource_spec_secret: "{{ credentialinputsource_spec.secret | mandatory }}"
