---
- name: Fetch Secret Record in _tower_secret_record
  k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ module_spec_secret }}"
    namespace: "{{ module_metadata_namespace }}"
  register: _tower_secret_record

- name: Assert _tower_secret_record
  assert:
    that:
      - _tower_secret_record["resources"] is defined
      - (_tower_secret_record["resources"] | length>0)
    fail_msg: "No data in secret {{ module_spec_secret }}"

- name: Assert _tower_secret_record.host
  assert:
    that:
      # yamllint disable-line rule:line-length
      - _tower_secret_record['resources'][0]['data']['host'] is defined
    fail_msg: "Missing token entry in {{ module_spec_secret }}"

- name: Assert _tower_secret_record.token
  assert:
    that:
      # yamllint disable-line rule:line-length
      - _tower_secret_record['resources'][0]['data']['token'] is defined
    fail_msg: "Missing token entry in {{ module_spec_secret }}"

- name: Assert tower_secret.verify_ssl
  assert:
    that:
      # yamllint disable-line rule:line-length
      - _tower_secret_record['resources'][0]['data']['verify_ssl'] is defined
    fail_msg: "Missing verify_ssl entry in {{ module_spec_secret }}"

- name: Set tower_secret_data (b64decoded)
  set_fact:
    tower_secret_data:
      # yamllint disable-line rule:line-length
      host: "{{ _tower_secret_record['resources'][0]['data']['host'] | b64decode }}"
      # yamllint disable-line rule:line-length
      token: "{{ _tower_secret_record['resources'][0]['data']['token'] | b64decode }}"
      # yamllint disable-line rule:line-length
      verify_ssl: "{{ _tower_secret_record['resources'][0]['data']['verify_ssl'] | b64decode }}"

- name: "Annotate CR with tower.ansible.com/host"
  k8s:
    definition:
      apiVersion: "{{ module_api_group}}/{{ module_api_version }}"
      kind: "{{ module_kind }}"
      metadata:
        name: "{{ module_metadata_name }}"
        namespace: "{{ module_metadata_namespace }}"
        annotations:
          "tower.ansible.com/host": "{{ tower_secret_data.host }}"
