---
- name: "Assert variables"
  assert:
    that:
      - organization_kind is defined
      - organization_kind is string
      - organization_api_group is defined
      - organization_api_group is string
      - organization_api_version is defined
      - organization_api_version is string
      - organization_finalize_state is defined
      - organization_finalize_state is in ['present', 'absent']
      - organization_metadata_name is defined
      - organization_metadata_name is string
      - organization_metadata_namespace is defined
      - organization_metadata_namespace is string
      - organization_module_name is defined
      - organization_module_name is in [ 'tower_organization' ]
      - organization_spec is defined
      - organization_spec is mapping
      - organization_spec_collection is defined
      - organization_spec_collection is in ['awx.awx', 'ansible.tower']
      - organization_spec_config is defined
      - organization_spec_config is mapping

- name: "organization: Calling desired state specific tasks"
  include_tasks: "{{ organization_spec_config.state | default('present') }}.yml"
