---
- name: "Assert variables"
  assert:
    that:
      - group_kind is defined
      - group_kind is string
      - group_api_group is defined
      - group_api_group is string
      - group_api_version is defined
      - group_api_version is string
      - group_finalize_state is defined
      - group_finalize_state is in ['present', 'absent']
      - group_metadata_name is defined
      - group_metadata_name is string
      - group_metadata_namespace is defined
      - group_metadata_namespace is string
      - group_module_name is defined
      - group_module_name is in [ 'tower_group' ]
      - group_spec is defined
      - group_spec is mapping
      - group_spec_collection is defined
      - group_spec_collection is in ['awx.awx', 'ansible.tower']
      - group_spec_config is defined
      - group_spec_config is mapping

- name: "group: Calling desired state specific tasks"
  include_tasks: "{{ group_spec_config.state | default('present') }}.yml"
