---
## { "ansible_operator_meta": {
##      "name": <object_name>,
##      "namespace": <object_namespace>,
##   },
##   <cr_spec_fields_as_snake_case>,
##   <watch vars>,
##   <finalizer vars>,
##   _<group_as_snake>_<kind>: {
##       <cr_object> as is
##   }
##   _<group_as_snake>_<kind>_spec: {
##       <cr_object.spec> as is
##   }
## }
# yamllint disable-line rule:line-length
user_kind: "User"
# yamllint disable-line rule:line-length
user_api_group: "tower.ansible.com"
# yamllint disable-line rule:line-length
user_api_version: "v1alpha1"
# yamllint disable-line rule:line-length
user_finalize_state: "{{ finalize_state | default('present', true) }}"
# yamllint disable-line rule:line-length
user_metadata_name: "{{ ansible_operator_meta.name }}"
# yamllint disable-line rule:line-length
user_metadata_namespace: "{{ ansible_operator_meta.namespace }}"
# yamllint disable-line rule:line-length
user_module_name: "tower_user"
# yamllint disable-line rule:line-length
user_spec: "{{ _tower_ansible_com_user.spec }}"
# yamllint disable-line rule:line-length
user_spec_collection: "{{ user_spec.collection | default('awx.awx') }}"
# yamllint disable-line rule:line-length
user_spec_config: "{{ user_spec.config | combine({'state': user_finalize_state}) }}"
# yamllint disable-line rule:line-length
user_spec_secret: "{{ user_spec.secret | mandatory }}"
